[package]
name = "app1"
version = "0.1.0"
authors = ["magnate <liangeaglejun@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
#[[bin]]
#name = "hell"
#path = "src/hell.rs"
